'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")>  _
Partial Friend NotInheritable Class Settings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()),Settings)
    
    Public Shared ReadOnly Property [Default]() As Settings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property DSPPath() As String
        Get
            Return CType(Me("DSPPath"),String)
        End Get
        Set
            Me("DSPPath") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property AshitaPath() As String
        Get
            Return CType(Me("AshitaPath"),String)
        End Get
        Set
            Me("AshitaPath") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("127.0.0.1")>  _
    Public Property mysql_host() As String
        Get
            Return CType(Me("mysql_host"),String)
        End Get
        Set
            Me("mysql_host") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("3306")>  _
    Public Property mysql_port() As String
        Get
            Return CType(Me("mysql_port"),String)
        End Get
        Set
            Me("mysql_port") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
    Public Property mysql_login() As String
        Get
            Return CType(Me("mysql_login"),String)
        End Get
        Set
            Me("mysql_login") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
    Public Property mysql_password() As String
        Get
            Return CType(Me("mysql_password"),String)
        End Get
        Set
            Me("mysql_password") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("dspdb")>  _
    Public Property mysql_database() As String
        Get
            Return CType(Me("mysql_database"),String)
        End Get
        Set
            Me("mysql_database") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ENABLE_COP() As Boolean
        Get
            Return CType(Me("ENABLE_COP"),Boolean)
        End Get
        Set
            Me("ENABLE_COP") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ENABLE_TOAU() As Boolean
        Get
            Return CType(Me("ENABLE_TOAU"),Boolean)
        End Get
        Set
            Me("ENABLE_TOAU") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ENABLE_WOTG() As Boolean
        Get
            Return CType(Me("ENABLE_WOTG"),Boolean)
        End Get
        Set
            Me("ENABLE_WOTG") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ENABLE_ACP() As Boolean
        Get
            Return CType(Me("ENABLE_ACP"),Boolean)
        End Get
        Set
            Me("ENABLE_ACP") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ENABLE_AMK() As Boolean
        Get
            Return CType(Me("ENABLE_AMK"),Boolean)
        End Get
        Set
            Me("ENABLE_AMK") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ENABLE_ASA() As Boolean
        Get
            Return CType(Me("ENABLE_ASA"),Boolean)
        End Get
        Set
            Me("ENABLE_ASA") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ENABLE_ABYSSEA() As Boolean
        Get
            Return CType(Me("ENABLE_ABYSSEA"),Boolean)
        End Get
        Set
            Me("ENABLE_ABYSSEA") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ENABLE_SOA() As Boolean
        Get
            Return CType(Me("ENABLE_SOA"),Boolean)
        End Get
        Set
            Me("ENABLE_SOA") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("[%d/%b %H:%M]")>  _
    Public Property timestamp_formatLogin() As String
        Get
            Return CType(Me("timestamp_formatLogin"),String)
        End Get
        Set
            Me("timestamp_formatLogin") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("no")>  _
    Public Property stdout_with_ansisequenceLogin() As String
        Get
            Return CType(Me("stdout_with_ansisequenceLogin"),String)
        End Get
        Set
            Me("stdout_with_ansisequenceLogin") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property console_silentLogin() As String
        Get
            Return CType(Me("console_silentLogin"),String)
        End Get
        Set
            Me("console_silentLogin") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("54002")>  _
    Public Property search_server_port() As String
        Get
            Return CType(Me("search_server_port"),String)
        End Get
        Set
            Me("search_server_port") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("DarkStar")>  _
    Public Property servername() As String
        Get
            Return CType(Me("servername"),String)
        End Get
        Set
            Me("servername") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property expire_auctions() As Boolean
        Get
            Return CType(Me("expire_auctions"),Boolean)
        End Get
        Set
            Me("expire_auctions") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
    Public Property expire_days() As Decimal
        Get
            Return CType(Me("expire_days"),Decimal)
        End Get
        Set
            Me("expire_days") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("3600")>  _
    Public Property expire_interval() As Decimal
        Get
            Return CType(Me("expire_interval"),Decimal)
        End Get
        Set
            Me("expire_interval") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property RESTRICT_BY_EXPANSION() As Boolean
        Get
            Return CType(Me("RESTRICT_BY_EXPANSION"),Boolean)
        End Get
        Set
            Me("RESTRICT_BY_EXPANSION") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("[%H:%M:%S]")>  _
    Public Property timestamp_formatMap() As String
        Get
            Return CType(Me("timestamp_formatMap"),String)
        End Get
        Set
            Me("timestamp_formatMap") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("no")>  _
    Public Property stdout_with_ansisequenceMap() As String
        Get
            Return CType(Me("stdout_with_ansisequenceMap"),String)
        End Get
        Set
            Me("stdout_with_ansisequenceMap") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property console_silentMap() As Decimal
        Get
            Return CType(Me("console_silentMap"),Decimal)
        End Get
        Set
            Me("console_silentMap") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1750")>  _
    Public Property buff_maxsize() As Decimal
        Get
            Return CType(Me("buff_maxsize"),Decimal)
        End Get
        Set
            Me("buff_maxsize") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
    Public Property max_time_lastupdate() As Decimal
        Get
            Return CType(Me("max_time_lastupdate"),Decimal)
        End Get
        Set
            Me("max_time_lastupdate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
    Public Property lightluggage_block() As Decimal
        Get
            Return CType(Me("lightluggage_block"),Decimal)
        End Get
        Set
            Me("lightluggage_block") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property vanadiel_time_offset() As Decimal
        Get
            Return CType(Me("vanadiel_time_offset"),Decimal)
        End Get
        Set
            Me("vanadiel_time_offset") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property no_auction_limits() As Boolean
        Get
            Return CType(Me("no_auction_limits"),Boolean)
        End Get
        Set
            Me("no_auction_limits") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property CoP_Battle_cap() As Boolean
        Get
            Return CType(Me("CoP_Battle_cap"),Boolean)
        End Get
        Set
            Me("CoP_Battle_cap") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ENABLE_COP_ZONE_CAP() As Boolean
        Get
            Return CType(Me("ENABLE_COP_ZONE_CAP"),Boolean)
        End Get
        Set
            Me("ENABLE_COP_ZONE_CAP") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property exp_rate() As Decimal
        Get
            Return CType(Me("exp_rate"),Decimal)
        End Get
        Set
            Me("exp_rate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property exp_loss_rate() As Decimal
        Get
            Return CType(Me("exp_loss_rate"),Decimal)
        End Get
        Set
            Me("exp_loss_rate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property exp_party_gap_penalties() As Decimal
        Get
            Return CType(Me("exp_party_gap_penalties"),Decimal)
        End Get
        Set
            Me("exp_party_gap_penalties") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property exp_retain() As Decimal
        Get
            Return CType(Me("exp_retain"),Decimal)
        End Get
        Set
            Me("exp_retain") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
    Public Property exp_loss_level() As Decimal
        Get
            Return CType(Me("exp_loss_level"),Decimal)
        End Get
        Set
            Me("exp_loss_level") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("75")>  _
    Public Property MAX_LEVEL() As Decimal
        Get
            Return CType(Me("MAX_LEVEL"),Decimal)
        End Get
        Set
            Me("MAX_LEVEL") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property speed_mod() As Decimal
        Get
            Return CType(Me("speed_mod"),Decimal)
        End Get
        Set
            Me("speed_mod") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property level_sync_enable() As Boolean
        Get
            Return CType(Me("level_sync_enable"),Boolean)
        End Get
        Set
            Me("level_sync_enable") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property all_jobs_widescan() As Boolean
        Get
            Return CType(Me("all_jobs_widescan"),Boolean)
        End Get
        Set
            Me("all_jobs_widescan") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property player_tp_multiplier() As Decimal
        Get
            Return CType(Me("player_tp_multiplier"),Decimal)
        End Get
        Set
            Me("player_tp_multiplier") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property player_hp_multiplier() As Decimal
        Get
            Return CType(Me("player_hp_multiplier"),Decimal)
        End Get
        Set
            Me("player_hp_multiplier") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property player_mp_multiplier() As Decimal
        Get
            Return CType(Me("player_mp_multiplier"),Decimal)
        End Get
        Set
            Me("player_mp_multiplier") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property player_stat_multiplier() As Decimal
        Get
            Return CType(Me("player_stat_multiplier"),Decimal)
        End Get
        Set
            Me("player_stat_multiplier") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("2.0")>  _
    Public Property sj_mp_divisor() As Decimal
        Get
            Return CType(Me("sj_mp_divisor"),Decimal)
        End Get
        Set
            Me("sj_mp_divisor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
    Public Property START_GIL() As Decimal
        Get
            Return CType(Me("START_GIL"),Decimal)
        End Get
        Set
            Me("START_GIL") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
    Public Property START_INVENTORY() As Decimal
        Get
            Return CType(Me("START_INVENTORY"),Decimal)
        End Get
        Set
            Me("START_INVENTORY") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("18")>  _
    Public Property SUBJOB_QUEST_LEVEL() As Decimal
        Get
            Return CType(Me("SUBJOB_QUEST_LEVEL"),Decimal)
        End Get
        Set
            Me("SUBJOB_QUEST_LEVEL") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
    Public Property ADVANCED_JOB_LEVEL() As Decimal
        Get
            Return CType(Me("ADVANCED_JOB_LEVEL"),Decimal)
        End Get
        Set
            Me("ADVANCED_JOB_LEVEL") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property UNLOCK_OUTPOST_WARPS() As Decimal
        Get
            Return CType(Me("UNLOCK_OUTPOST_WARPS"),Decimal)
        End Get
        Set
            Me("UNLOCK_OUTPOST_WARPS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ALL_MAPS() As Boolean
        Get
            Return CType(Me("ALL_MAPS"),Boolean)
        End Get
        Set
            Me("ALL_MAPS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property audit_chat() As Boolean
        Get
            Return CType(Me("audit_chat"),Boolean)
        End Get
        Set
            Me("audit_chat") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property audit_say() As Boolean
        Get
            Return CType(Me("audit_say"),Boolean)
        End Get
        Set
            Me("audit_say") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property audit_shout() As Boolean
        Get
            Return CType(Me("audit_shout"),Boolean)
        End Get
        Set
            Me("audit_shout") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property audit_tell() As Boolean
        Get
            Return CType(Me("audit_tell"),Boolean)
        End Get
        Set
            Me("audit_tell") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property audit_yell() As Boolean
        Get
            Return CType(Me("audit_yell"),Boolean)
        End Get
        Set
            Me("audit_yell") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property audit_linkshell() As Boolean
        Get
            Return CType(Me("audit_linkshell"),Boolean)
        End Get
        Set
            Me("audit_linkshell") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property audit_party() As Boolean
        Get
            Return CType(Me("audit_party"),Boolean)
        End Get
        Set
            Me("audit_party") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property mob_tp_multiplier() As Decimal
        Get
            Return CType(Me("mob_tp_multiplier"),Decimal)
        End Get
        Set
            Me("mob_tp_multiplier") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property mob_hp_multiplier() As Decimal
        Get
            Return CType(Me("mob_hp_multiplier"),Decimal)
        End Get
        Set
            Me("mob_hp_multiplier") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property nm_hp_multiplier() As Decimal
        Get
            Return CType(Me("nm_hp_multiplier"),Decimal)
        End Get
        Set
            Me("nm_hp_multiplier") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property mob_mp_multiplier() As Decimal
        Get
            Return CType(Me("mob_mp_multiplier"),Decimal)
        End Get
        Set
            Me("mob_mp_multiplier") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property nm_mp_multiplier() As Decimal
        Get
            Return CType(Me("nm_mp_multiplier"),Decimal)
        End Get
        Set
            Me("nm_mp_multiplier") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property mob_stat_multiplier() As Decimal
        Get
            Return CType(Me("mob_stat_multiplier"),Decimal)
        End Get
        Set
            Me("mob_stat_multiplier") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property nm_stat_multiplier() As Decimal
        Get
            Return CType(Me("nm_stat_multiplier"),Decimal)
        End Get
        Set
            Me("nm_stat_multiplier") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
    Public Property drop_rate_multiplier() As Decimal
        Get
            Return CType(Me("drop_rate_multiplier"),Decimal)
        End Get
        Set
            Me("drop_rate_multiplier") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
    Public Property INITIAL_LEVEL_CAP() As Decimal
        Get
            Return CType(Me("INITIAL_LEVEL_CAP"),Decimal)
        End Get
        Set
            Me("INITIAL_LEVEL_CAP") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property OPENING_CUTSCENE_ENABLE() As Boolean
        Get
            Return CType(Me("OPENING_CUTSCENE_ENABLE"),Boolean)
        End Get
        Set
            Me("OPENING_CUTSCENE_ENABLE") = value
        End Set
    End Property
End Class
